name: Build app

on:
  push:
    tags:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    name: Linux - Rust app
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0

      - run: ls -la

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-linux
          retention-days: 1
          path: ./

  build_windows:
    name: Windows - Rust app
    runs-on: windows-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0

      - run: dir

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-windows
          retention-days: 1
          path: ./

  package:
    name: Upload release
    runs-on: ubuntu-22.04
    needs: [build_windows, build_linux]
    steps:
      # Download generated artifacts
      - name: Retrieve artifact Windows
        uses: actions/download-artifact@main
        with:
          name: artifact-windows
          path: ./artifact_windows

      - name: Retrieve artifact Linux
        uses: actions/download-artifact@main
        with:
          name: artifact-linux
          path: ./artifact_linux

      # Create Linux zip
      #- run: mkdir bidibip
      #- run: mv ./artifact_rust_linux/bidibip ./bidibip/
      #- run: zip -r bidibip_linux.zip ./bidibip/
      #- run: rm -r ./bidibip

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            bidibip_linux.zip
            bidibip_windows.zip
